version: 2
jobs:
  build:
    working_directory: ~/circleci-kloudformation-generator
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        keys:
        - gradle-{{ checksum "build.gradle.kts" }}
    - run: ./gradlew build -DBUILD_NUM=$CIRCLE_BUILD_NUM
    - store_artifacts:
        path: build/libs
    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-{{ checksum "build.gradle.kts" }}